onEvent('jei.hide.items', event => {
    event.hide('avaritia:iron_singularity')
    event.hide('avaritia:gold_singularity')
    event.hide('avaritia:lapis_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
    // event.hide('avaritia:iron_singularity')
  })